# Build stage
FROM node:18 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build:prod

# Run stage
FROM nginx:latest
# 复制构建好的 dist 目录到镜像中
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 48088
CMD ["nginx", "-g", "daemon off;"]
