# Build stage
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl ctbc-admin -am

# Run stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/ctbc-admin/target/ctbc-admin.jar app.jar
EXPOSE 48089
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["java", "-jar", "app.jar"]
